local sf = require 'sampfuncs'
local key = require 'vkeys'
local dlstatus = require('moonloader').download_status
cstart = 1
function submenus_show(menu, caption, select_button, close_button, back_button)
    select_button, close_button, back_button = select_button or 'Select', close_button or 'Close', back_button or 'Back'
    prev_menus = {}
    function display(menu, id, caption)
        local string_list = {}
        for i, v in ipairs(menu) do
            table.insert(string_list, type(v.submenu) == 'table' and v.title .. '  >>' or v.title)
        end
        sampShowDialog(id, caption, table.concat(string_list, '\n'), select_button, (#prev_menus > 0) and back_button or close_button, sf.DIALOG_STYLE_LIST)
        repeat
            wait(0)
            local result, button, list = sampHasDialogRespond(id)
            if result then
                if button == 1 and list ~= -1 then
                    local item = menu[list + 1]
                    if type(item.submenu) == 'table' then -- submenu
                        table.insert(prev_menus, {menu = menu, caption = caption})
                        if type(item.onclick) == 'function' then
                            item.onclick(menu, list + 1, item.submenu)
                        end
                        return display(item.submenu, id + 1, item.submenu.title and item.submenu.title or item.title)
                    elseif type(item.onclick) == 'function' then
                        local result = item.onclick(menu, list + 1)
                        if not result then return result end
                        return display(menu, id, caption)
                    end
                else -- if button == 0
                    if #prev_menus > 0 then
                        local prev_menu = prev_menus[#prev_menus]
                        prev_menus[#prev_menus] = nil
                        return display(prev_menu.menu, id - 1, prev_menu.caption)
                    end
                    return false
                end
            end
        until result
    end
    return display(menu, 31337, caption or menu.title)
end

local my_dialog = {
    {
        title = '{9966CC}Лекция: {ffffff}Вводная лекция',
        onclick = function()
            sampSendChat("Итак, Вы поступили в Кадетский корпус SFPD.")
            wait(5000)
            sampSendChat("Для начала, забудьте о таких фразах, как: никак нет, так точно и.т.д.")
            wait(5000)
            sampSendChat("В обязанности кадета входит:")
            wait(5000)
            sampSendChat("Охрана КПП на постах A и B, подробнее на экскурсии.")
            wait(1500)
            sampSendChat("/time")
            wait(500)
            setVirtualKeyDown(key.VK_F8, true)
            wait(150)
            setVirtualKeyDown(key.VK_F8, false)
            wait(2500)
            sampSendChat("По заступлению, покиданию и нахождению на посту 5 минут докладывать в рацию.")
            wait(5000)
            sampSendChat("Посещать все лекции, уроки, тренировки.")
            wait(5000)
            sampSendChat("Носить форму и значок своего отдела.")
            wait(5000)
            sampSendChat("Вам запрещено: ")
            wait(1500)
            sampSendChat("/time")
            wait(500)
            setVirtualKeyDown(key.VK_F8, true)
            wait(150)
            setVirtualKeyDown(key.VK_F8, false)
            wait(2500)
            sampSendChat("Покидать пост без доклада в рацию, спать на посту, оставлять КПП закрытым, после покидания поста.")
            wait(5000)
            sampSendChat("Покидать участок без разрешения.")
            wait(5000)
            sampSendChat("Проводить задержание граждан, объявлять в розыск, выписывать штрафы. ")
            wait(5000)
            sampSendChat("Использовать табельное оружие против преступников, только в целях самообороны. ")
            wait(1500)
            sampSendChat("/time")
            wait(500)
            setVirtualKeyDown(key.VK_F8, true)
            wait(150)
            setVirtualKeyDown(key.VK_F8, false)
            wait(2500)
            sampSendChat("По окончании рабочего дня, уходить на выходной не переодевшись. ")
            wait(5000)
            sampSendChat("Вам разрешено: ")
            wait(5000)
            sampSendChat("По окончанию рабочего дня, уходить на выходной, улучшать навыки владением оружия. ")
            wait(5000)
            sampSendChat("Спать только в оружейной комнате. ")
            wait(1500)
            sampSendChat("/time")
            wait(500)
            setVirtualKeyDown(key.VK_F8, true)
            wait(150)
            setVirtualKeyDown(key.VK_F8, false)
            wait(2500)
            sampSendChat("Экзамен на повышение проводится через два дня после перевода с армии или через пять дней если с гражданки. ")
            wait(5000)
            sampSendChat("Экзамен состоит из УК, ТШ, ФП, правил использования рез. пуль, наручников и базы данных. ")
            wait(5000)
            sampSendChat("Также, что самое важное, вам потребуется пройти практическую часть. ")
            wait(5000)
            sampSendChat("Она состоит из ареста условного нарушителя и выписывания штрафа водителю.")
            wait(1500)
            sampSendChat("/time")
            wait(500)
            setVirtualKeyDown(key.VK_F8, true)
            wait(150)
            setVirtualKeyDown(key.VK_F8, false)
            wait(2500)
            sampSendChat("Чтобы лучше подготовиться к практике, вы будете выезжать на посты с инструкторами. ")
            wait(5000)
            sampSendChat("Со всем необходимым материалом для сдачи экзаменов вы можете ознакомиться на офф портале. ")
            wait(5000)
            sampSendChat("ВАЖНО! Вам нужно отписаться на офф. портале штата, ")
            wait(5000)
            sampSendChat("для того что-бы вас допустили до сдачи экзамена.")
            wait(1500)
            sampSendChat("/time")
            wait(500)
            setVirtualKeyDown(key.VK_F8, true)
            wait(150)
            setVirtualKeyDown(key.VK_F8, false)
        end
    },
    {
        title = '{9966CC}Лекция: {ffffff}Общение с гражданскими',
        onclick = function()
            sampSendChat("Сейчас я проведу вам лекцию на тему Обращение с гражданскими. ")
            wait(5000)
            sampSendChat("Действия при прибытии гражданских на КПП")
            wait(5000)
            sampSendChat("Когда к КПП подъезжает ЛЮБОЙ гражданский, вы обязаны представится")
            wait(5000)
            sampSendChat("Пример: Здравия желаю, офицер полиции Иван Иванов")
            wait(1500)
            sampSendChat("/time")
            wait(500)
            setVirtualKeyDown(key.VK_F8, true)
            wait(150)
            setVirtualKeyDown(key.VK_F8, false)
            wait(2500)
            sampSendChat("После попросить показать вам его документы")
            wait(5000)
            sampSendChat("Если это сотрудник SFPD, то вы должны его пропустить и пожелать удачной службы")
            wait(5000)
            sampSendChat("После этого доложить в рацию, что в часть прибыл такой-то")
            wait(5000)
            sampSendChat("Если это гражданский, которому запрещено находиться на территории участка")
            wait(1500)
            sampSendChat("/time")
            wait(500)
            setVirtualKeyDown(key.VK_F8, true)
            wait(150)
            setVirtualKeyDown(key.VK_F8, false)
            wait(2500)
            sampSendChat("То вы должны спросить его цель прибытия")
            wait(5000)
            sampSendChat("Если он приехал к кому-то из сотрудников, то доложить об этом в рацию")
            wait(5000)
            sampSendChat("И попросить гражданского ожидать на кпп")
            wait(5000)
            sampSendChat("Если у него нет весомых причин прибывания на охраняемой территории,")
            wait(1500)
            sampSendChat("/time")
            wait(500)
            setVirtualKeyDown(key.VK_F8, true)
            wait(150)
            setVirtualKeyDown(key.VK_F8, false)
            wait(2500)
            sampSendChat("Вы должны сказать ему, что он должен покинуть территорию ")
            wait(5000)
            sampSendChat("- Покиньте территорию, или мы будем вынуждены арестовать Вас по статье за неподчинение.")
            wait(5000)
            sampSendChat("В случае отказа покинуть территорию, вызываете по рации офицеров для проведения ареста.")
            wait(5000)
            sampSendChat("Просто так на КПП огонь по гражданским не открывать, только в случае нападения на пост.")
            wait(5000)
            sampSendChat("Лекция закончена, вопросы есть?")
            wait(1500)
            sampSendChat("/time")
            wait(500)
            setVirtualKeyDown(key.VK_F8, true)
            wait(150)
            setVirtualKeyDown(key.VK_F8, false)
        end
    },
    {
      title = '{9966CC}Лекция: {ffffff}Резиновые пули',
      onclick = function()
        sampSendChat("Приветствую, сейчас я проведу вам лекцию. ")
        wait(5000)
        sampSendChat("Тема лекции: «Резиновые пули»")
        wait(5000)
        sampSendChat("У каждого сотрудника Полиции есть резиновые пули.")
        wait(5000)
        sampSendChat("Резиновые пули подходят для такого оружия, как Deagle и Shotgun.")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Резиновые пули предназначены для любой дистанции.")
        wait(5000)
        sampSendChat("Резиновые пули способны «сбить» человека с ног.")
        wait(5000)
        sampSendChat("Резиновые пули можно использовать:")
        wait(5000)
        sampSendChat("Для того, чтобы обездвижить нарушителя, преступника на некоторое время.")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("После того, как вы обездвижили его, то лучше сразу провести обыск.")
        wait(5000)
        sampSendChat("У нарушителя может быть оружие, если есть нужно сразу изъять его.")
        wait(5000)
        sampSendChat("Запрещено использовать резиновые пули в перестрелке, исключение: если стреляют не в вас.")
        wait(5000)
        sampSendChat("На этом лекция окончена.")
        wait(5000)
        sampSendChat("У кого есть вопросы по этой лекции?")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
      end
    },
    {
      title = '{9966CC}Лекция: {ffffff}Правила езды колонной',
      onclick = function()
        sampSendChat("Приветствую вас на лекции о правилах езды колонной.")
        wait(5000)
        sampSendChat("Сегодня я расскажу о правилах езды колонной.")
        wait(5000)
        sampSendChat("Начну с того, что запрещено делать при езде колонной.")
        wait(5000)
        sampSendChat("Запрещено превышать общую скорость колонны, 50 км/ч.")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Запрещено покидать колонну и обгонять участников колонны.")
        wait(5000)
        sampSendChat("Нужно соблюдать ПДД, нельзя нарушать данные правила.")
        wait(5000)
        sampSendChat("За рулем автомобилей в колонне должны быть самые опытные водители,")
        wait(5000)
        sampSendChat("ведь любая ошибка, может создать угрозу для всей колонны.")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("На этом у меня все, спасибо за внимание.")
        wait(5000)
        sampSendChat("У кого есть вопросы?")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
      end
    },
    {
      title = '{9966CC}Лекция: {ffffff}Проверка документов',
      onclick = function()
        sampSendChat("Приветствую всех, сейчас я проведу лекцию на тему проверка документов")
        wait(5000)
        sampSendChat("Перед проверкой гражданина, вы обязаны представиться.")
        wait(5000)
        sampSendChat("Пример: Офицер Иванов, предъявите Ваши документы.")
        wait(5000)
        sampSendChat("/b /do На груди висит полицейский жетон SAPD - SF.")
          wait(1500)
          sampSendChat("/time")
          wait(500)
          setVirtualKeyDown(key.VK_F8, true)
          wait(150)
          setVirtualKeyDown(key.VK_F8, false)
          wait(2500)
        sampSendChat("Запрещено проверять документы у граждан, которые ничего при Вас не нарушили.")
        wait(5000)
        sampSendChat("Проверяете документы только у личностей, которые при вас нарушили закон.")
        wait(5000)
        sampSendChat("Проверка документов осуществляется на месте.")
        wait(5000)
        sampSendChat("Если гражданин забыл их, вы едите в участок полиции для установления личности.")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Если гражданин сопротивляется или не хочет,")
        wait(5000)
        sampSendChat("То объявляете в розыск по статье 7.1, неподчинение.")
        wait(5000)
        sampSendChat("На этом лекция окончена.")
        wait(5000)
        sampSendChat("У кого есть вопросы по этой лекции?")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
      end
    },
    {
      title = '{9966CC}Лекция: {ffffff}Юрисдикция',
      onclick = function()
        sampSendChat("Приветствую, сейчас я проведу вам лекцию, на тему: Юрисдикция")
        wait(5000)
        sampSendChat("Юрисдикция — закрепленная область несения службы.")
        wait(5000)
        sampSendChat("За пределами юрисдикции нельзя производить арест, обыск и так далее.")
        wait(5000)
        sampSendChat("Если вам надо выехать за границы юрисдикции, то вы просите разрешение.")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Разрешение выдаёт только Майоры и выше.")
        wait(5000)
        sampSendChat("После того, как в волну департамента прозвучит сообщение,")
        wait(5000)
        sampSendChat("О том, что вы отпущены в другой город Вы можете въехать в другой город.")
        wait(5000)
        sampSendChat("После выезда из границы юрисдикции запрещено вести свою службу, а именно:")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Объявлять в розыск,проводить обыск,проводить изъятие и тому подобное.")
        wait(5000)
        sampSendChat("Также, если вы погнались за преступником и он уехал в другую юрисдикцию, то")
        wait(5000)
        sampSendChat("преследование вести можно для задержания, разрешения просить не надо.")
        wait(5000)
        sampSendChat("Как вы остановили преступника вы вызываете местных коллег")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("И везёте преступника в участок")
        wait(5000)
        sampSendChat("На этом лекция окончена.")
        wait(5000)
        sampSendChat("У кого есть вопросы по этой лекции?")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
      end
    },
    {
      title = '{9966CC}Лекция: {ffffff}Общение с коллегами',
      onclick = function()
        sampSendChat("Приветствую, сейчас я проведу лекцию на тему Общения с коллегами.")
        wait(5000)
        sampSendChat("Сотрудник должен быть вежливым при общении с коллегами")
        wait(5000)
        sampSendChat("В полицейском департаменте нет армейского обращения Так точно, Никак нет, и так далее ")
        wait(5000)
        sampSendChat("младшие сотрудники должны выполнять приказы начальства и должны уважительно относиться к ним. ")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Обращаться к начальству на Вы, должны быть дисциплинированными. ")
        wait(5000)
        sampSendChat("Сотрудники департамента обязаны соблюдать субординацию при общении со старшими по званию или должности ")
        wait(5000)
        sampSendChat("Сотрудники могут обращаться на Ты к коллегам, которые находятся в их отделе без")
        wait(5000)
        sampSendChat("использование мата или другой ненормативной лексики ")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Ко всем другим сотрудникам, которые выше Вас по должности или званию - обращаться на Вы.")
        wait(5000)
        sampSendChat("На этом всё, благодарю за внимание ")
        wait(5000)
        sampSendChat("У кого есть вопросы?")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
      end
    },
    {
      title = '{9966CC}Лекция: {ffffff}Тир',
      onclick = function()
        sampSendChat("Сейчас я проведу вам короткую лекцию, на тему: Тир ")
        wait(5000)
        sampSendChat("Тир — место, специально приспособленное для целевой и учебной стрельбы.")
        wait(5000)
        sampSendChat("Тир находится в оружейной комнате участка, за дверью.")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Если вы решили улучшить навык владения каким нибудь оружием, или же")
        wait(5000)
        sampSendChat("научиться из него стрелять, то вы должны спросить это у Майора и выше.")
        wait(5000)
        sampSendChat("Обязательно нужно взять со склада коробку с патронами.")
        wait(5000)
        sampSendChat("После рабочего дня или перерыва можно посещать свободно тир.")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Не забывайте надевать наушники перед началом стрельбы.")
        wait(5000)
        sampSendChat("За нарушение последует наказание.")
        wait(5000)
        sampSendChat("На этом лекция окончена.")
        wait(5000)
        sampSendChat("У кого есть вопросы по этой лекции?")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
      end
    },
    {
      title = '{9966CC}Лекция: {ffffff}Правила подачи в розыск',
      onclick = function()
        sampSendChat("Тема лекции: Объявление в розыск ")
        wait(5000)
        sampSendChat("И так, выдавать розыск разрешено только лицам, которые нарушили закон.")
        wait(5000)
        sampSendChat("Выдавать розыск нужно согласно статье, которое соответствует нарушению.")
        wait(5000)
        sampSendChat("Категорически запрещено:")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Придумывать новые статьи.")
        wait(5000)
        sampSendChat("Давать розыск, если вы сами не видели нарушения или не провели расследование.")
        wait(5000)
        sampSendChat("Смешивание нескольких статей.")
        wait(5000)
        sampSendChat("В розыск объявляем по описанию статьи. ")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("На этом лекция окончена.")
        wait(5000)
        sampSendChat("У кого есть вопросы по этой лекции?")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
      end
    },
    {
      title = '{9966CC}Лекция: {ffffff}Угроза терракта',
      onclick = function()
        sampSendChat("Лекция на тему угроза теракта")
        wait(5000)
        sampSendChat("Всегда контролируйте ситуацию вокруг себя, особенно, когда патрулируете жилые места")
        wait(5000)
        sampSendChat("При обнаружении подозрительных вещей, не трогая их, вызовите спец.отряд ")
        wait(5000)
        sampSendChat("Не подбирайте бесхозных вещей, как бы привлекательно они не выглядели. В них могут быть замаскированы взрывные устройства")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Eсли вы обнаружили неизвестный предмет около домов, опросите соседей, возможно, он принадлежит им ")
        wait(5000)
        sampSendChat("Если этот предмет не никому принадлежит ,эвакуируйте ближайшие дома. ")
        wait(5000)
        sampSendChat("Если вы обнаружили неизвестный предмет в учреждении, немедленно сообщите находке о администрации или охране.")
        wait(5000)
        sampSendChat("И как можно быстрее эвакуируйте людей и оцепите учреждения.")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Зафиксируйте время обнаружения предмета")
        wait(5000)
        sampSendChat("Постарайтесь как можно быстрее оцепить место , чтобы люди отошли как можно дальше от находки. ")
        wait(5000)
        sampSendChat("В качестве камуфляжа используются самые обычные бытовые предметы: сумки, пакеты, коробки, игрушки и т.п.")
        wait(5000)
        sampSendChat("После прибытия спец отделов вы должны заняться эвакуацией остальных людей, которые находятся рядом с находкой.")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("На этом лекция закончена.")
        wait(5000)
        sampSendChat("У кого есть вопросы по ней?")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
      end
    },
    {
      title = '{9966cc}Лекция: {ffffff}Лекция для армий',
      onclick = function()
            local _, myid = sampGetPlayerIdByCharHandle(PLAYER_PED)
        sampSendChat("/s Здравия желаю, дорогие военнослужащие! ")
        wait(5000)
        sampSendChat("/s Я, " ..sampGetPlayerNickname(myid):gsub('_', ' ').. " , сотрудник отдела полицейской академии SFPD ")
        wait(5000)
        sampSendChat("/s Сегодня я хочу провести для вас лекцию... ")
        wait(5000)
        sampSendChat("/s о работе полицейского департамента San Fierro. ")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("/s Департамент включает в себя следующие отделы, такие как:")
        wait(5000)
        sampSendChat("/s Patrol Service, отдел который занимается поимкой преступников, ")
        wait(5000)
        sampSendChat("/s охраной правопорядка в городе. ")
        wait(5000)
        sampSendChat("/s Ключевой отдел, в который попадает каждый новый ")
        wait(5000)
        sampSendChat("/s сотрудник нашего департамента. ")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("/s Следующий отдел, это отдел Полицейская Академия. ")
        wait(5000)
        sampSendChat("/s Отдел занимается кадровой подготовкой ")
        wait(5000)
        sampSendChat("/s и обучением будущих офицеров полиции.")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("/s Так же у нас имеется Детективный отдел, ")
        wait(5000)
        sampSendChat("/s который занимается расследованиями запутанных преступлений.")
        wait(5000)
        sampSendChat("/s И, последний отдел, - это SWAT. ")
        wait(5000)
        sampSendChat("/s Элитное спецподразделение департамента, ")
        wait(5000)
        sampSendChat("/s которое участвует в спец. операциях, ")
        wait(5000)
        sampSendChat("/s и обеспечивает порядок на улицах города, ")
        wait(5000)
        sampSendChat("/s так же занимается поимкой преступников. ")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("/s Для того чтобы поступить на службу к нам в полицию,")
        wait(2000)
        sampSendChat("/s Вам необходимо: ")
        wait(5000)
        sampSendChat("/s Иметь звание от младшего сержанта, ")
        wait(5000)
        sampSendChat("/s лицензия на оружие и не иметь криминальное прошлое. ")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("/s После поступления к нам на службу, ")
        wait(5000)
        sampSendChat("/s вы автоматически зачисляетесь в полицейскую академию. ")
        wait(5000)
        sampSendChat("/s Где проходите обучение не менее чем два дня, ")
        wait(5000)
        sampSendChat("/s а после - допускаетесь к сдаче экзамена и получаете ")
        wait(5000)
        sampSendChat("/s очередное повышение в звании: Офицер. ")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("/s Если имеете желание служить в полиции и подходите по критериям, ")
        wait(5000)
        sampSendChat("На этом моя лекция закончена.")
        wait(5000)
        sampSendChat("/s У кого есть вопросы - задавайте.")
      end
    },
    {
      title = '{9966CC}Лекция: {ffffff}Лекция новым сотрудникам PS',
      onclick = function()
        sampSendChat("Итак, Вы поступили в Patrol Service SFPD. ")
        wait(5000)
        sampSendChat("Для начала смените значок на новый под номером 31 ")
        wait(5000)
        sampSendChat("В обязанности офицера входит: стоять на постах АВСФ, АШ, SFa, SFn ")
        wait(5000)
        sampSendChat("Эти посты будут показаны на экскурсии, после лекции. ")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("По заступлению, покиданию и нахождению на посту 5 минут докладывать в рацию. ")
        wait(5000)
        sampSendChat("Наводить порядок на постах, пресекать нарушения закона ")
        wait(5000)
        sampSendChat("Соблюдать субординацию при общении с гражданами и сотрудниками гос. структур. ")
        wait(5000)
        sampSendChat("Носить форму и значок своего отдела. ")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Вам запрещено: ")
        wait(5000)
        sampSendChat("Покидать пост без доклада в рацию, спать на посту, оставлять основные посты пустыми. ")
        wait(5000)
        sampSendChat("Неадекватно общаться с гражданами и гос. сотрудниками. ")
        wait(5000)
        sampSendChat("По окончании рабочего дня, уходить на выходной не переодевшись. ")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Вам разрешено: ")
        wait(5000)
        sampSendChat("По окончанию рабочего дня, уходить на выходной, улучшать навыки владением оружия. ")
        wait(5000)
        sampSendChat("Спать только в оружейной комнате. ")
        wait(5000)
        sampSendChat("Проводить аресты, выписывать штрафы, использовать табельное оружие, а так же резиновые пули. ")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Желательно чаще проводить допросы, а потом выкладывать отчёт о них на оф.сайт, чтобы начальство видело вашу работу ")
        wait(5000)
        sampSendChat("Основные посты: АВСФ, АШ. Их стоит занимать первыми. ")
        wait(5000)
        sampSendChat("Транспорт отдела PS - это патрульные автомобили и мотоциклы (с сержанта) ")
        wait(5000)
        sampSendChat("Остальные т/с предназначены для других отделов, вертолёт берётся в случае необходимости и с разрешения старших ")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
        wait(2500)
        sampSendChat("Общее повышение проводится в среду и воскресенье, допуски расставляются согласно правилам повышения. ")
        wait(5000)
        sampSendChat("Обязательно сообщите главе или зам. главы вашего отдела, что вы теперь в их отделе.")
        wait(1500)
        sampSendChat("/time")
        wait(500)
        setVirtualKeyDown(key.VK_F8, true)
        wait(150)
        setVirtualKeyDown(key.VK_F8, false)
      end
    },
    {
      title = '{FF8C00}Остальное: {FFFFFF}Надеть значок Стажера ПА',
      onclick = function()
        sampSendChat("/me надел значок Стажера ПА")
        wait(1500)
        sampSendChat("/clist 28")
      end
    },
    {
      title = '{ff8c00}Остальное: {ffffff}Надеть значок Инструктора ПА',
      onclick = function()
        sampSendChat("/me надел значок Инструктора ПА")
        wait(1500)
        sampSendChat("/clist 15")
      end
    },
    {
      title = '{ff8c00}Остальное: {ffffff}Надеть значок Зам.Нач.ПА',
      onclick = function()
        sampSendChat("/me надел значок Зам.Нач.ПА")
        wait(1500)
        sampSendChat("/clist 12")
      end
    },
    {
      title = '{ff8c00}Остальное: {ffffff}Написать кадетам про покушать(Как Стажер ПА)',
    onclick = function()
      local _, myid = sampGetPlayerIdByCharHandle(PLAYER_PED)
      sampSendChat(string.format("/r [Стажер ПА] Кадеты, кого вывезти покушать пишите на п.%s", myid))
    end
  },
  {
    title = '{ff8c00}Остальное: {ffffff}Написать кадетам про покушать(Как Инструктор ПА)',
  onclick = function()
    local _, myid = sampGetPlayerIdByCharHandle(PLAYER_PED)
    sampSendChat(string.format("/r [Инструктор ПА] Кадеты, кого вывезти покушать пишите на п.%s", myid))
  end
},
{
  title = '{ff8c00}Остальное: {ffffff}Написать кадетам про покушать(Как Зам.Нач.ПА)',
onclick = function()
  local _, myid = sampGetPlayerIdByCharHandle(PLAYER_PED)
  sampSendChat(string.format("/r [Зам.Нач.ПА] Кадеты, кого вывезти покушать пишите на п.%s", myid))
end
},
{
  title = '{ff8c00}Остальное: {ffffff}Поставить метку на штаб PA',
  onclick = function()
    result, pickup = createPickup(19605, 19, -2635.1477050781, 261.07876586914, 4.328125)
    marker = addBlipForPickup(pickup)
  end
}
}

function main()
  while not isSampAvailable() do wait(1000) end
  if cstart == 1 then
    sampAddChatMessage("PA Menu loaded.", -1)
  end
  sampRegisterChatCommand('pundate', pupdate)
  while true do wait(0)
    if wasKeyPressed(key.VK_F2) then
      submenus_show(my_dialog, 'PA Menu')
    end
  end
end

function pupdate()
  downloadUrlToFile("https://github.com/WhackerH/kirya/blob/master/shpora.luac?raw=true", thisScript().path, function(id, status)
  if status == dlstatus.STATUS_ENDDOWNLOADDATA then
    thisScript():reload()
  end
end)
end
